import AsyncStorage from '@react-native-async-storage/async-storage';
import * as MediaLibrary from "expo-media-library";
import * as Sharing from "expo-sharing";
import * as FileSystem from 'expo-file-system';
import * as IntentLauncher from 'expo-intent-launcher';

const ExportItemMaster = async(action) => {
  const cData = await AsyncStorage.getItem("companyData");
  if(!cData){
       alert("No Company Exists");
       return;
    }
  const companyData = JSON.parse(cData);
  let iString = await AsyncStorage.getItem("items");
  if(!iString){
        alert("No Items Exist To Download");
        return;
  }
  const items = JSON.parse(iString);
  const unitMap = {};
  const getItemTemplate = (item,index) => {
    const li = item.unit.split(" - ");
    const short = li.length > 1 ? li[0] : item.unit;
    unitMap[item.unit] = true;
    return `
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
     <STOCKITEM NAME="${item.name}" RESERVEDNAME="">
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
       <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
      </OLDAUDITENTRYIDS.LIST>
      <GUID>7cfe22bd-c6ad-4501-a6a4-a3a920dcd6a4-0000000${index}</GUID>
      <PARENT/>
      <CATEGORY/>
      <GSTAPPLICABLE>&#4; Applicable</GSTAPPLICABLE>
      <TAXCLASSIFICATIONNAME/>
      <GSTTYPEOFSUPPLY>Goods</GSTTYPEOFSUPPLY>
      <EXCISEAPPLICABILITY>&#4; Applicable</EXCISEAPPLICABILITY>
      <SALESTAXCESSAPPLICABLE/>
      <VATAPPLICABLE>&#4; Applicable</VATAPPLICABLE>
      <COSTINGMETHOD>Avg. Cost</COSTINGMETHOD>
      <VALUATIONMETHOD>Avg. Price</VALUATIONMETHOD>
      <BASEUNITS>${short}</BASEUNITS>
      <ADDITIONALUNITS/>
      <EXCISEITEMCLASSIFICATION/>
      <VATBASEUNIT>${short}</VATBASEUNIT>
      <ISCOSTCENTRESON>No</ISCOSTCENTRESON>
      <ISBATCHWISEON>No</ISBATCHWISEON>
      <ISPERISHABLEON>No</ISPERISHABLEON>
      <ISENTRYTAXAPPLICABLE>No</ISENTRYTAXAPPLICABLE>
      <ISCOSTTRACKINGON>No</ISCOSTTRACKINGON>
      <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
      <ASORIGINAL>Yes</ASORIGINAL>
      <ISRATEINCLUSIVEVAT>No</ISRATEINCLUSIVEVAT>
      <IGNOREPHYSICALDIFFERENCE>No</IGNOREPHYSICALDIFFERENCE>
      <IGNORENEGATIVESTOCK>No</IGNORENEGATIVESTOCK>
      <TREATSALESASMANUFACTURED>No</TREATSALESASMANUFACTURED>
      <TREATPURCHASESASCONSUMED>No</TREATPURCHASESASCONSUMED>
      <TREATREJECTSASSCRAP>No</TREATREJECTSASSCRAP>
      <HASMFGDATE>No</HASMFGDATE>
      <ALLOWUSEOFEXPIREDITEMS>No</ALLOWUSEOFEXPIREDITEMS>
      <IGNOREBATCHES>No</IGNOREBATCHES>
      <IGNOREGODOWNS>No</IGNOREGODOWNS>
      <ADJDIFFINFIRSTSALELEDGER>No</ADJDIFFINFIRSTSALELEDGER>
      <ADJDIFFINFIRSTPURCLEDGER>No</ADJDIFFINFIRSTPURCLEDGER>
      <CALCONMRP>No</CALCONMRP>
      <EXCLUDEJRNLFORVALUATION>No</EXCLUDEJRNLFORVALUATION>
      <ISMRPINCLOFTAX>No</ISMRPINCLOFTAX>
      <ISADDLTAXEXEMPT>No</ISADDLTAXEXEMPT>
      <ISSUPPLEMENTRYDUTYON>No</ISSUPPLEMENTRYDUTYON>
      <GVATISEXCISEAPPL>No</GVATISEXCISEAPPL>
      <REORDERASHIGHER>No</REORDERASHIGHER>
      <MINORDERASHIGHER>No</MINORDERASHIGHER>
      <ISEXCISECALCULATEONMRP>No</ISEXCISECALCULATEONMRP>
      <INCLUSIVETAX>No</INCLUSIVETAX>
      <GSTCALCSLABONMRP>No</GSTCALCSLABONMRP>
      <MODIFYMRPRATE>No</MODIFYMRPRATE>
      <ALTERID> 209</ALTERID>
      <DENOMINATOR> 1</DENOMINATOR>
      <RATEOFVAT>0</RATEOFVAT>
      <VATBASENO> 1</VATBASENO>
      <VATTRAILNO> 1</VATTRAILNO>
      <VATACTUALRATIO> 1</VATACTUALRATIO>
      <SERVICETAXDETAILS.LIST>      </SERVICETAXDETAILS.LIST>
      <VATDETAILS.LIST>      </VATDETAILS.LIST>
      <SALESTAXCESSDETAILS.LIST>      </SALESTAXCESSDETAILS.LIST>
      <GSTDETAILS.LIST>
       <APPLICABLEFROM>20210401</APPLICABLEFROM>
       <CALCULATIONTYPE>On Value</CALCULATIONTYPE>
       <HSNCODE>${item.hsn}</HSNCODE>
       <HSNMASTERNAME/>
       <HSN>${item.name}</HSN>
       <TAXABILITY>Taxable</TAXABILITY>
       <ISREVERSECHARGEAPPLICABLE>No</ISREVERSECHARGEAPPLICABLE>
       <ISNONGSTGOODS>No</ISNONGSTGOODS>
       <GSTINELIGIBLEITC>No</GSTINELIGIBLEITC>
       <INCLUDEEXPFORSLABCALC>No</INCLUDEEXPFORSLABCALC>
       <STATEWISEDETAILS.LIST>
        <STATENAME>&#4; Any</STATENAME>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>Central Tax</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
         <GSTRATE> ${parseFloat(item.rates) / 2}</GSTRATE>
        </RATEDETAILS.LIST>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>State Tax</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
         <GSTRATE> ${parseFloat(item.rates) / 2}</GSTRATE>
        </RATEDETAILS.LIST>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>Integrated Tax</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
         <GSTRATE> ${parseFloat(item.rates)}</GSTRATE>
        </RATEDETAILS.LIST>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
        </RATEDETAILS.LIST>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>Cess on Qty</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Quantity</GSTRATEVALUATIONTYPE>
        </RATEDETAILS.LIST>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>State Cess</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
        </RATEDETAILS.LIST>
        <GSTSLABRATES.LIST>        </GSTSLABRATES.LIST>
       </STATEWISEDETAILS.LIST>
       <TEMPGSTDETAILSLABRATES.LIST>       </TEMPGSTDETAILSLABRATES.LIST>
      </GSTDETAILS.LIST>
      <LANGUAGENAME.LIST>
       <NAME.LIST TYPE="String">
        <NAME>${item.name}</NAME>
       </NAME.LIST>
       <LANGUAGEID> 1033</LANGUAGEID>
      </LANGUAGENAME.LIST>
      <SCHVIDETAILS.LIST>      </SCHVIDETAILS.LIST>
      <EXCISETARIFFDETAILS.LIST>      </EXCISETARIFFDETAILS.LIST>
      <TCSCATEGORYDETAILS.LIST>      </TCSCATEGORYDETAILS.LIST>
      <TDSCATEGORYDETAILS.LIST>      </TDSCATEGORYDETAILS.LIST>
      <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
      <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
      <MRPDETAILS.LIST>      </MRPDETAILS.LIST>
      <VATCLASSIFICATIONDETAILS.LIST>      </VATCLASSIFICATIONDETAILS.LIST>
      <COMPONENTLIST.LIST>      </COMPONENTLIST.LIST>
      <ADDITIONALLEDGERS.LIST>      </ADDITIONALLEDGERS.LIST>
      <SALESLIST.LIST>      </SALESLIST.LIST>
      <PURCHASELIST.LIST>      </PURCHASELIST.LIST>
      <FULLPRICELIST.LIST>      </FULLPRICELIST.LIST>
      <BATCHALLOCATIONS.LIST>      </BATCHALLOCATIONS.LIST>
      <TRADEREXCISEDUTIES.LIST>      </TRADEREXCISEDUTIES.LIST>
      <STANDARDCOSTLIST.LIST>      </STANDARDCOSTLIST.LIST>
      <STANDARDPRICELIST.LIST>      </STANDARDPRICELIST.LIST>
      <EXCISEITEMGODOWN.LIST>      </EXCISEITEMGODOWN.LIST>
      <MULTICOMPONENTLIST.LIST>      </MULTICOMPONENTLIST.LIST>
      <LBTDETAILS.LIST>      </LBTDETAILS.LIST>
      <PRICELEVELLIST.LIST>      </PRICELEVELLIST.LIST>
      <GSTCLASSFNIGSTRATES.LIST>      </GSTCLASSFNIGSTRATES.LIST>
      <EXTARIFFDUTYHEADDETAILS.LIST>      </EXTARIFFDUTYHEADDETAILS.LIST>
      <TEMPGSTITEMSLABRATES.LIST>      </TEMPGSTITEMSLABRATES.LIST>
     </STOCKITEM>
    </TALLYMESSAGE>`;
  }
	

  const getUnitTemplate = (unit,index) => {
     const li = unit.split(" - ");
     const short = li.length > 1 ? li[0] : unit;
     const name = li.length > 1 ? li[1] : unit;
     return `
     <TALLYMESSAGE xmlns:UDF="TallyUDF">
         <UNIT NAME="${short}" RESERVEDNAME="">
          <NAME>${short}</NAME>
          <GUID>7cfe22bd-c6ad-4501-a6a4-a3a920dcd6a4-000000a1</GUID>
          <ORIGINALNAME>${name}</ORIGINALNAME>
          <GSTREPUOM>${unit}</GSTREPUOM>
          <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
          <ASORIGINAL>Yes</ASORIGINAL>
          <ISGSTEXCLUDED>No</ISGSTEXCLUDED>
          <ISSIMPLEUNIT>Yes</ISSIMPLEUNIT>
          <ALTERID> 175</ALTERID>
          <DECIMALPLACES> 2</DECIMALPLACES>
         </UNIT>
     </TALLYMESSAGE>`;
  }

  const itemList =  Object.values(items).map(getItemTemplate).join("");

  const unitList = Object.keys(unitMap).map(getUnitTemplate).join("");

	const mainbody = `
  <ENVELOPE>
		 <HEADER>
		  <TALLYREQUEST>Import Data</TALLYREQUEST>
		 </HEADER>
		 <BODY>
		  <IMPORTDATA>
		   <REQUESTDESC>
		    <REPORTNAME>All Masters</REPORTNAME>
		    <STATICVARIABLES>
		     <SVCURRENTCOMPANY>${companyData.name}</SVCURRENTCOMPANY>
		    </STATICVARIABLES>
		   </REQUESTDESC>
		   <REQUESTDATA>
        ${unitList}
		    <TALLYMESSAGE xmlns:UDF="TallyUDF">
		     <CURRENCY NAME="₹" RESERVEDNAME="">
		      <GUID>7cfe22bd-c6ad-4501-a6a4-a3a920dcd6a4-0000001d</GUID>
		      <MAILINGNAME>INR</MAILINGNAME>
		      <ORIGINALNAME>₹</ORIGINALNAME>
		      <EXPANDEDSYMBOL>INR</EXPANDEDSYMBOL>
		      <DECIMALSYMBOL>paise</DECIMALSYMBOL>
		      <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
		      <ASORIGINAL>Yes</ASORIGINAL>
		      <ISSUFFIX>No</ISSUFFIX>
		      <HASSPACE>Yes</HASSPACE>
		      <INMILLIONS>No</INMILLIONS>
		      <ALTERID> 196</ALTERID>
		      <DECIMALPLACES> 2</DECIMALPLACES>
		      <DECIMALPLACESFORPRINTING> 2</DECIMALPLACESFORPRINTING>
		      <DAILYSTDRATES.LIST>      </DAILYSTDRATES.LIST>
		      <DAILYBUYINGRATES.LIST>      </DAILYBUYINGRATES.LIST>
		      <DAILYSELLINGRATES.LIST>      </DAILYSELLINGRATES.LIST>
		     </CURRENCY>
		    </TALLYMESSAGE>
		    <TALLYMESSAGE xmlns:UDF="TallyUDF">
		     <CURRENCY NAME="₹" RESERVEDNAME="">
		      <GUID>7cfe22bd-c6ad-4501-a6a4-a3a920dcd6a4-0000001d</GUID>
		      <MAILINGNAME>INR</MAILINGNAME>
		      <ORIGINALNAME>₹</ORIGINALNAME>
		      <EXPANDEDSYMBOL>INR</EXPANDEDSYMBOL>
		      <DECIMALSYMBOL>paise</DECIMALSYMBOL>
		      <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
		      <ASORIGINAL>Yes</ASORIGINAL>
		      <ISSUFFIX>No</ISSUFFIX>
		      <HASSPACE>Yes</HASSPACE>
		      <INMILLIONS>No</INMILLIONS>
		      <ALTERID> 196</ALTERID>
		      <DECIMALPLACES> 2</DECIMALPLACES>
		      <DECIMALPLACESFORPRINTING> 2</DECIMALPLACESFORPRINTING>
		      <DAILYSTDRATES.LIST>      </DAILYSTDRATES.LIST>
		      <DAILYBUYINGRATES.LIST>      </DAILYBUYINGRATES.LIST>
		      <DAILYSELLINGRATES.LIST>      </DAILYSELLINGRATES.LIST>
		     </CURRENCY>
		    </TALLYMESSAGE>
		    <TALLYMESSAGE xmlns:UDF="TallyUDF">
		      <GODOWN NAME="Main Location" RESERVEDNAME="">
			      <GUID>7cfe22bd-c6ad-4501-a6a4-a3a920dcd6a4-0000003e</GUID>
			      <PARENT/>
			      <JOBNAME/>
			      <ARE1SERIALMASTER/>
			      <ARE2SERIALMASTER/>
			      <ARE3SERIALMASTER/>
			      <TAXUNITNAME/>
			      <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
			      <ASORIGINAL>Yes</ASORIGINAL>
			      <HASNOSPACE>No</HASNOSPACE>
			      <HASNOSTOCK>No</HASNOSTOCK>
			      <ISEXTERNAL>No</ISEXTERNAL>
			      <ISINTERNAL>No</ISINTERNAL>
			      <ENABLEEXPORT>No</ENABLEEXPORT>
			      <ISPRIMARYEXCISEUNIT>No</ISPRIMARYEXCISEUNIT>
			      <ALLOWEXPORTREBATE>No</ALLOWEXPORTREBATE>
			      <ISTRADERRGNUMBERON>No</ISTRADERRGNUMBERON>
			      <ALTERID> 63</ALTERID>
			      <LANGUAGENAME.LIST>
			       <NAME.LIST TYPE="String">
			        <NAME>Main Location</NAME>
			       </NAME.LIST>
			       <LANGUAGEID> 1033</LANGUAGEID>
			      </LANGUAGENAME.LIST>
			      <SCHVIDETAILS.LIST>      </SCHVIDETAILS.LIST>
			      <EXCISETARIFFDETAILS.LIST>      </EXCISETARIFFDETAILS.LIST>
			      <SERIALNUMBERLIST.LIST>      </SERIALNUMBERLIST.LIST>
			      <EXCISEMFGDETAILS.LIST>      </EXCISEMFGDETAILS.LIST>
			      <EXCISELUTDETAILS.LIST>      </EXCISELUTDETAILS.LIST>
			      <EXCISEBONDDETAILS.LIST>      </EXCISEBONDDETAILS.LIST>
			      <EXCISERANGEDETAILS.LIST>      </EXCISERANGEDETAILS.LIST>
			      <EXCISEDIVISIONDETAILS.LIST>      </EXCISEDIVISIONDETAILS.LIST>
			      <EXCISECOMMISSIONERATEDETAILS.LIST>      </EXCISECOMMISSIONERATEDETAILS.LIST>
			      <EXTARIFFDUTYHEADDETAILS.LIST>      </EXTARIFFDUTYHEADDETAILS.LIST>
		     </GODOWN>
		    </TALLYMESSAGE>
        ${itemList}
		   </REQUESTDATA>
		  </IMPORTDATA>
		 </BODY>
	</ENVELOPE>`

   const saveFile = async () => {
     
     if(action == "download"){
      const permissions = await FileSystem.StorageAccessFramework.requestDirectoryPermissionsAsync();

      if (permissions.granted) {
        const uri = permissions.directoryUri;

        const newFile = await FileSystem.StorageAccessFramework.createFileAsync(
            uri,
            "items.xml",
            "xml"
        );
        await FileSystem.writeAsStringAsync(newFile, mainbody, { encoding: FileSystem.EncodingType.UTF8 });

        alert(`Files Downloaded Successfully`);
      }
    }
    else{
      let fileUri = FileSystem.documentDirectory + "items.xml";
      await FileSystem.writeAsStringAsync(fileUri, mainbody, { encoding: FileSystem.EncodingType.UTF8 });
      await Sharing.shareAsync(fileUri)
      .catch((err) => console.log('Sharing::error', err))
    }
      
  }

  await saveFile();

}

export default ExportItemMaster;